Add support for existing canvas in webgl addon
daonb/xterm.js pull request #1
Opened 2023-02-07 16:27 UTC by eyal-sasson

See #4379.

2023-03-21 15:46 UTC, daonb requested changes

2023-03-21 15:46 UTC, daonb commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +    this._gl.disable(this._gl.SCISSOR_TEST);
This line should probably be deleted

2023-03-21 15:46 UTC, daonb commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +    start = clamp(start, terminal.rows - 1, 0);
I'm not sure why we you've added this

2023-03-21 15:46 UTC, daonb commented on css/xterm.css
> +.xterm .xterm-accessible-buffer div {
Why did you change the class's name?

2023-03-21 15:46 UTC, daonb commented on demo/index.html.old
Should probably be removed

2023-03-21 15:46 UTC, daonb commented on src/browser/AccessibleBuffer.ts
Not sure how this file was released to the change

2023-03-22 15:24 UTC, eyal-sasson commented
Your fork is behind so you're seeing some unrelated changes as mine.

2023-04-07 05:55 UTC, daonb commented on addons/xterm-addon-webgl/typings/xterm-addon-webgl.d.ts
> +    constructor(canvas?: HTMLCanvasElement, preserveDrawingBuffer?: boolean)
It's much better to add new parameters after the existing ones so you don't break existing function calls.
Also, add the ';' atthe end of the line.

2023-04-07 05:55 UTC, daonb commented on src/browser/AccessibleBuffer.ts
> +  private _isAccessibleBufferActive: boolean = false;
Changing the name of properties results in many line changes. Better to keep the existing names.

2023-04-10 09:10 UTC, eyal-sasson commented on src/browser/AccessibleBuffer.ts
> +  private _isAccessibleBufferActive: boolean = false;
I definitely didn't touch this one, might be a diff problem between your fork and the main repo.

2026-03-03 13:58 UTC, closed without merging